### ISSUE TITLE
Challenge 1 Feedback

### ISSUE THREAD

**Issue by meredithcat** [jayceazua/cs2.2#1]
Challenge 1 Feedback: 6/20
Feedback based on Challenge 1 Rubric

- Solution: 1 (x2 = 2)
  - Does not run on sample input file without error (small fix)
  - Does not print vertices and edges from the Graph object, so allows duplicate edges

- Documentation: 1
  - Add docstrings to all methods, such as parse_edge

- Organization: 2
  - Vertex and edge info is being printed directly from the input file rather than from the Graph object.
  - Graph and file handling are too tightly coupled, e.g. in grab_graph_info which should have a clear responsibility (make graph, return it).

- Testing: 1
  - Include unit tests for Vertex, Graph, file handling
  - Use self.assert* for more flexible asserts

**Comment by aespaldi** [comment]
Challenge 1 Regrade on 8/13 - no changes.

**Comment by jayceazua** [comment]
I ran it with the file and it works I don't understand where you see the error?
The code runs please run code again... I run the script with the file and it works?

**Comment by jayceazua** [comment]
<img width="491" alt="Screen Shot 2019-08-10 at 9 45 54 AM" src="https://user-images.githubusercontent.com/24749332/62824494-b97a7200-bb53-11e9-9c91-61ad5d0afde6.png">

**Comment by jayceazua** [comment]
The script to run is `$ python3 challenge_1.py graph_data.txt`
