### ISSUE TITLE
Challenge 3 Feedback

### ISSUE THREAD

**Issue by aespaldi** [jayceazua/cs2.2#3]
no code submitted 0/24

**Comment by jayceazua** [comment]
> no code submitted 0/24
Please take a look here:
https://github.com/jayceazua/cs2.2/tree/master/challenges/challenge_3

**Comment by jayceazua** [comment]
<img width="1057" alt="Screen Shot 2019-08-10 at 9 49 35 AM" src="https://user-images.githubusercontent.com/24749332/62824512-31e13300-bb54-11e9-819b-c85b7a8ef853.png">
